### ISSUE TITLE
12/72 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by Teggles** [nicolasdejong/ShakeMouseToLocate#9]
![Screenshot 2024-09-09 010911](https://github.com/user-attachments/assets/e4382fa6-5dea-4929-b6a5-8402d0ea71f0)

**Comment by nicolasdejong** [comment]
Thanks for letting me know. I've read before that this is apparently a false-positive related to the tool used to generate the exe. But if so many scanners flag this exe it may not be a false positive. So it is better to just remove it, just in case.
